### ISSUE TITLE
Update sleep_timer default 

### ISSUE THREAD

**Issue by BOsterbuhr** [BOsterbuhr/FEC-Data-Wranglin#3]
Default should be 3600 seconds to equal 1 hour.

Update:
Line 175        sleep_timer: int = 3600
Line 181        sleep_timer: int (default=3600)
Line 201        time.sleep(sleep_timer)

https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/35f80d716327fba959b491b138f3daa1ab4281db/src/data/data_fetcher.py#L175

https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/35f80d716327fba959b491b138f3daa1ab4281db/src/data/data_fetcher.py#L181

https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/35f80d716327fba959b491b138f3daa1ab4281db/src/data/data_fetcher.py#L201

**Comment by NapsterInBlue** [comment]
That anybody pays me money to code is baffling, lol
