### ISSUE TITLE
What is this? 

### ISSUE THREAD

**Issue by BOsterbuhr** [BOsterbuhr/FEC-Data-Wranglin#4]
Why is -> str outside the ()?
https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/e0ce967e2fd68f9b9d61ce415d5717c30a801e59/src/data/data_fetcher.py#L53
https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/e0ce967e2fd68f9b9d61ce415d5717c30a801e59/src/data/data_fetcher.py#L54
What is with the -> str? 
https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/e0ce967e2fd68f9b9d61ce415d5717c30a801e59/src/data/data_fetcher.py#L55

**Comment by NapsterInBlue** [comment]
Good question!

This is called [type-hinting](https://docs.python.org/3/library/typing.html), and it's basically a loose way to specify the data type going into/out of a function.

Not only does it make your code more readable, most IDE's (I've been enjoying [VS Code](https://code.visualstudio.com/), myself) support it to where it will inspect the type hints and allow you to inspect data types just by hovering over them.

![image](https://user-images.githubusercontent.com/3505365/101262243-26cbf200-370b-11eb-909f-dfeb8ca4dedd.png)

Which tends to be really handy when your programs get increasingly complicated, e.g.

![image](https://user-images.githubusercontent.com/3505365/101262567-d609c880-370d-11eb-9e8b-bae77d8503df.png)

**Comment by BOsterbuhr** [comment]
I have been using VS Code but probably not as efficiently as I could but it is a very very nice environment.

**Comment by NapsterInBlue** [comment]
I've only started really using it in the last couple of months, but only use the basics. I'm sure if I took the time, I could really get it configured nicely, but I just haven't.

Need to rewatch this talk soon...

https://www.youtube.com/watch?v=I56oFTm9UlE
