### ISSUE TITLE
Update to api_calls_per_hour?

### ISSUE THREAD

**Issue by BOsterbuhr** [BOsterbuhr/FEC-Data-Wranglin#5]
https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/e0ce967e2fd68f9b9d61ce415d5717c30a801e59/src/data/data_fetcher.py#L202
This should be updated to api_calls_per_hour right? To reset after the wait time.

**Comment by NapsterInBlue** [comment]
Yup, absolutely. Replaced all references to `little_count` manually, and must of missed this one. Good eye!
