### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by NapsterInBlue** [BOsterbuhr/FEC-Data-Wranglin#9]
Added [a commit that introduces a bit of unit testing](https://github.com/BOsterbuhr/FEC-Data-Wranglin/commit/cda057ed3cc8d30b89bb5619f2e5546be3e3ea9e). This is really good practice as well-- both in terms of Python Development and getting used to Git/GitHub

### Configure Git

I don't use Macs, but if memory serves correctly, they *should* come with `git`, batteries-included. What you're going to want to do is configure it so that you can use your Terminal to interface with GitHub.

You do that by [setting up your name/email](https://support.atlassian.com/bitbucket-cloud/docs/configure-your-dvcs-username-for-commits/) and (optionally, but highly-recommended) [setting up your SSH credentials so you don't have to put in your password each time you make a change](https://docs.github.com/en/free-pro-team@latest/github/using-git/caching-your-github-credentials-in-git)

### Get the Code Locally

Now what I'd like for you to do pull the code down locally by

1. Just like [the first step in the other issue](https://github.com/BOsterbuhr/FEC-Data-Wranglin/issues/8#issuecomment-739412351), make a new branch off of `big_refactor`, called `big_refactor_test` or something like that.
2. Click the Download button and copy the URL (I don't think there's a huge difference between HTTPS and SSH)

![image](https://user-images.githubusercontent.com/3505365/101265894-59c8b280-3718-11eb-97b6-3cf9de6276f4.png)

3. Open up the terminal, navigate to a directory where you want to drop this project (let's keep it separate from your existing code for now) and type `git clone` and then paste this URL. This should pull all of your code down locally.

4. Go into the directory with `cd FEC-Data-Wranglin`

5. Establish a new working branch with

`git checkout -b <your branch name> origin/<your_branch_name>`

Essentially what this is doing is:

* `checkout`: I want to work on the branch
* `-b`: A *new* branch, at that
* `<your branch name>`: that we'll call `<your branch name>`
* `origin/<your_branch_name>`: that's based on the code on GitHub (`origin`) called `<your_branch_name>`

### Onto Python

As far as the project goes, I took this chunk of the code

https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/big_refactor/src/data/data_fetcher.py#L85-L91

and made it reference two new functions

https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/big_refactor/src/data/data_fetcher.py#L106-L140

What I'd like you to do is rewrite `_handle_recipient_committee_type()` such that it:

1. Accepts lower-case input arguments
2. Cleans up the length of the `if`/`elif` statements (hint: consider googling "python in list")

Doing so, will allow your code to pass the unit tests I wrote (hence the introduction of `conftest.py` and `tests/` at the root.

To run them:

1. First, install `pytest` via `pip install pytest`
2. Then navigate to the **root** of your project `/FEC-Data-Wranglin` and type `pytest`. Doing so at the beginning, will yield a bunch of fails

![image](https://user-images.githubusercontent.com/3505365/101265916-98f70380-3718-11eb-999c-93ddb304fd27.png)

along with printouts of what the result was vs what the expected value was.

3. Change the code, run the tests, change the code, run the tests, rinse, repeat, until you see a less-ominous `pytest` message

![image](https://user-images.githubusercontent.com/3505365/101265938-d360a080-3718-11eb-93b2-b6c96158012e.png)

4. Once it's all good you'll run something that looks like

![image](https://user-images.githubusercontent.com/3505365/101265967-0e62d400-3719-11eb-9208-b93c0b2d8fef.png)

The final line should give you something "success"-sounding, like

![image](https://user-images.githubusercontent.com/3505365/101266035-9517b100-3719-11eb-92be-08ca3532196d.png)

**Comment by NapsterInBlue** [comment]
Okay. That ought to take you a minute or two.

Supposing it doesn't, however, here's some great resources that go over this stuff:

1. [How to think about Git](https://www.youtube.com/watch?v=1ffBJ4sVUb4&t=1s) (watch at 2x, if you think it's boring. This is a great intro talk.)
2. [This banger tutorial that I got started with](http://think-like-a-git.net/)

And if you have time, this is an all-timer tech talk as far as I'm concerned :)

https://www.youtube.com/watch?v=RZ4Sn-Y7AP8

**Comment by BOsterbuhr** [comment]
Ok that was fun lol, I learned a lot and that process is so much nicer than uploading files view the browser. 
Plus Git and VS Code together is very very nice, I could get used to this.

Also I skipped step 3...

<img width="1128" alt="Screen Shot 2020-12-05 at 9 11 33 PM" src="https://user-images.githubusercontent.com/34581663/101270671-ec7d4780-3740-11eb-943c-9242482862fd.png">

### Not going to lie that felt pretty good.

Before I forget, I stumbled upon [this](https://towardsdatascience.com/fuzzy-matching-at-scale-84f2bfd0c536) the other day and I am intrigued and terrified. 

I am guessing next step is to write the tests for `TestTransactionPeriod`?
Next guess is there is a better way to write `_handle_two_year_transaction_period()`?

**Comment by BOsterbuhr** [comment]
Well I did those steps and I somehow managed to make `_handle_two_year_transaction_period()` more complicated. It works but it is not anywhere close to pretty. Ideas?

**Comment by NapsterInBlue** [comment]
Fuckin right, my dude!

Soon, you'll be writing tests you don't even need just to get the 𝒢 𝑅 𝐸 𝐸 𝒩   𝒟 𝒪 𝒯 𝒮    𝒪 𝐹    𝒜 𝒞 𝐻 𝐼 𝐸 𝒱 𝐸 𝑀 𝐸 𝒩 𝒯 haha


------

### What verifying test coverage looks like on my end

1. I opened up my terminal and typed `git pull`. This basically goes out to GitHub and pulls down any changes. 

![image](https://user-images.githubusercontent.com/3505365/101291633-4250fe80-37d8-11eb-8e54-1cdf9a6036f0.png)

You'll notice the `[new branch]` where it picks up your... well, new branch

2. I want to verify that your tests pass (this is automateable, but way outside the scope of our little side project for now, haha), so I'll check out your version of the code with

![image](https://user-images.githubusercontent.com/3505365/101291696-cb683580-37d8-11eb-9718-300b2a8647ac.png)

this ominous `detached HEAD state` basically means "this is what the code looks like, but you're not actually working in the project anymore." If I wanted to _work_ on this branch, I'd follow the prompt they provide.

3. Now I clear my terminal with CTRL+L (Windows, baybeeee) and you'll notice the teal `(main)` has now changed to a double-parentheses and the commit hash (watch that Git for Ages 4 and Up, if that's unclear. The concept of HEAD is paramount.). I'm using Git Bash on Windows, your terminal might look like this, it might not, idk, lol

![image](https://user-images.githubusercontent.com/3505365/101291729-f3579900-37d8-11eb-83fe-e986f8c585bf.png)

4. Then, I see that everything passes :)

![image](https://user-images.githubusercontent.com/3505365/101291836-b3dd7c80-37d9-11eb-909d-5fcc9899261a.png)

------

Leave this issue open and open a Pull Request. I'll do an actual code review there!

**Comment by NapsterInBlue** [comment]
Gonna go make dinner, but now that you've got a PR opened up, you can link this issue to auto-resolve once the code is merged!

![image](https://user-images.githubusercontent.com/3505365/101295253-77664c80-37ea-11eb-84df-d58efc9c7af2.png)

**Comment by NapsterInBlue** [comment]
Huh. I really thought this would auto-close after I merged.

![image](https://user-images.githubusercontent.com/3505365/101417877-887e8e80-38ba-11eb-9004-a6b89c1cdc17.png)
